language: node_js

node_js:
  - 0.10.42

install:
  - npm install

script:
  - ./test/install.sh && npm run cover

# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"

notifications:
  slack: research-technologies:izdZdry8NEjrDmTjbHL5dCA8
